namespace HSK3
{
    public class Database
    {
        // Chữ Hán (word) - Câu ví dụ (sentence) - Pinyin - Hán Việt - Nghĩa - Biến âm
        public static string[][] han = {
            new string[] { "爱", "妹妹爱唱歌，也喜欢跳舞。", "ài", "ái", "yêu" },
            new string[] { "八", "两瓶啤酒，一个笔记本，一共三十块八角五分。", "bā", "bát", "số tám" },
            new string[] { "爸爸", "我从小就喜欢运动，这可能和爸爸是体育老师有关系。", "bà ba", "bá bá", "cha, bố" },
            new string[] { "杯子", "不用，你把筷子和杯子拿过来就可以了。", "bēi zi", "bôi tử", "ly, tách" },
            new string[] { "北京", "你把我们在北京玩儿的照片发给我吧？", "běi jīng", "bắc kinh", "Bắc Kinh" },
            new string[] { "本", "那你问问老王，我记得他有这本书。", "běn", "bản", "cuốn, quyển" },
            new string[] { "不", "你别看它个子不高，但跑起来比其他马都快。", "bù", "bất", "không" },
            new string[] { "不客气", "不客气，祝你生日快乐！", "bù kè qì", "bất khách khí", "đừng khách khí" },
            new string[] { "菜", "快点儿吧，一起吃，菜冷了就不好吃了。", "cài", "thái", "rau, món ăn" },
            new string[] { "茶", "先来一杯红茶，谢谢。", "chá", "trà", "trà" },
            new string[] { "吃", "妈，我快迟到了，早饭我不吃了。", "chī", "xích", "ăn" },
            new string[] { "出租车", "他今天有点事， 我叫了辆出租车，几分钟后就到楼下。", "chū zū chē", "xuất tô xa", "taxi" },
            new string[] { "打电话", "好，等一会儿下班后我给你打电话。", "dǎ diàn huà", "đả điện thoại", "gọi điện thoại" },
            new string[] { "大", "这件事情对叔叔的影响很大。", "dà", "đại", "to, lớn" },
            new string[] { "的", "这件事情对叔叔的影响很大。", "de", "đích", "(định ngữ)" },
            new string[] { "点", "今天我想早点儿回家。", "diǎn", "điểm", "giờ" },
            new string[] { "电脑", "现在用电脑和手机上网很方便，年轻人都喜欢在网上聊天儿。", "diàn nǎo", "điện não", "máy vi tính" },
            new string[] { "电视", "不要让你的孩子爱上电视。", "diàn shì", "điện thị", "truyền hình, TV" },
            new string[] { "电影", "我有两张明天晚上的电影票，一起去看吧？", "diàn yǐng", "điện ảnh", "phim" },
            new string[] { "东西", "放儿子房间，这两个箱子里都是他的东西。", "dōng xī", "đông tây", "đồ đạc" },
            new string[] { "都", "放儿子房间，这两个箱子里都是他的东西。", "dōu", "đô", "đều" },
            new string[] { "读", "他选择去北京读书。", "dú", "độc", "đọc" },
            new string[] { "对不起", "对不起，我明晚要参加一个比赛，没办法和你去了。", "duì bù qǐ", "đối bất khởi", "xin lỗi" },
            new string[] { "多", "谢谢你的关心，我的脚已经好多了，能站起来了。", "duō", "đa", "nhiều" },
            new string[] { "多少", "这里一共有多少只猫？", "duō shǎo", "đa thiểu", "bao nhiêu" },
            new string[] { "儿子", "那是我叔叔的儿子， 一岁多了。", "èr zǐ", "nhi tử", "con trai" },
            new string[] { "二", "都等了快二十分钟了，一辆车也没来。", "èr", "nhị", "số hai" },
            new string[] { "饭馆", "你们上次去的那个饭馆儿离这儿远吗？", "fàn guǎn", "phạn quán", "quán ăn" },
            new string[] { "飞机", "我明天早上的飞机，今天中午有时间见个面吗？", "fēi jī", "phi cơ", "máy bay" },
            new string[] { "分钟", "等一会儿，比赛还有三分钟就结束了。", "fēn zhōng", "phân chung", "phút" },
            new string[] { "高兴", "弟弟高兴地笑了。", "gāo xìng", "cao hứng", "vui mừng" },
            new string[] { "个", "他正在开会，您半个小时以后再打，好吗？", "ge", "cá", "cái" },
            new string[] { "工作", "她叫张晴，是今年秋天参加工作的，现在教三年级的数学。", "gōng zuò", "công tác", "công việc" },
            new string[] { "狗", "他不喜欢小狗。", "gǒu", "cẩu", "con chó" },
            new string[] { "汉语", "汉语必须要好，而且要了解中国文化。", "hàn yǔ", "hán ngữ", "tiếng Hán" },
            new string[] { "好", "汉语必须要好，而且要了解中国文化。", "hǎo", "hảo", "tốt, khỏe" },
            new string[] { "喝", "把菜单儿给我，我们喝杯绿茶吧？", "hē", "hát", "uống" },
            new string[] { "和", "现在用电脑和手机上网很方便，年轻人都喜欢在网上聊天儿。", "hé", "hòa", "và" },
            new string[] { "很", "现在用电脑和手机上网很方便，年轻人都喜欢在网上聊天儿。", "hěn", "ngận", "rất" },
            new string[] { "后面", "我的车在楼后面，车号后四位是六五二零。", "hòu miàn", "hậu diện", "phía sau" },
            new string[] { "回", "你回班里找几个学生帮忙拿一下。", "huí", "hồi", "về" },
            new string[] { "会", "外面又刮风又下雨的，不会影响飞机起飞吧？", "huì", "hội", "sẽ, biết" },
            new string[] { "火车站", "您可以选择火车站附近的宾馆，住那儿会更方便。", "huǒ chē zhàn", "hỏa xa trạm", "ga xe lửa" },
            new string[] { "几", "你回班里找几个学生帮忙拿一下。", "jǐ", "kỷ", "mấy" },
            new string[] { "家", "哥哥生病了，这两天妈妈一直在家里照顾他。", "jiā", "gia", "nhà, gia đình" },
            new string[] { "叫", "她叫张晴，是今年秋天参加工作的，现在教三年级的数学。", "jiào", "khiếu", "kêu, bị, để" },
            new string[] { "今天", "今天我想早点儿回家。", "jīn tiān", "kim thiên", "hôm nay" },
            new string[] { "九", "现在已经九点一刻了，你要去的话就快点儿", "jiǔ", "cửu", "số chín" },
            new string[] { "开", "小王，帮我开一下门，好吗？谢谢！", "kāi", "khai", "mở, nở, lái (xe)" },
            new string[] { "看", "我看你都没怎么动筷子，是不是不爱吃羊肉？", "kàn", "khán", "xem, trông, thăm, khám" },
            new string[] { "看见", "最近怎么一直没看见他？", "kàn jiàn", "khán kiến", "nhìn thấy" },
            new string[] { "块", "三楼还有一个这样的房子，但要贵十几万块钱。", "kuài", "khối", "tệ, đồng" },
            new string[] { "来", "您是来参加今天会议的吗？", "lái", "lai", "đến" },
            new string[] { "老师", "我从小就喜欢运动，这可能和爸爸是体育老师有关系。", "lǎo shī", "lão sư", "thầy, cô" },
            new string[] { "了", "这几年，我去了很多国家和城市。", "le", "liễu", "rồi" },
            new string[] { "冷", "快点儿吧，一起吃，菜冷了就不好吃了。", "lěng", "lãnh", "lạnh" },
            new string[] { "里", "您的箱子里有一瓶水，这是不能带上飞机的。", "lǐ", "lí", "trong" },
            new string[] { "零", "你明天到办公室找我，我在七零七。", "líng", "linh", "số không" },
            new string[] { "六", "别的都不错，就是没电梯，六层高了点儿。", "liù", "lục", "số sáu" },
            new string[] { "妈妈", "你好，我想买些花送给妈妈。", "mā ma", "ma ma", "mẹ" },
            new string[] { "吗", "外国人办银行卡需要护照。您带了吗？", "ma", "ma", "phải không?" },
            new string[] { "买", "还不错，你要买蛋糕吗？", "mǎi", "mãi", "mua" },
            new string[] { "猫", "这里一共有多少只猫？", "māo", "miêu", "con mèo" },
            new string[] { "没关系", "没关系。我们去看看三层那个吧。", "méi guān xi", "một quan kế", "không sao" },
            new string[] { "没", "没有。除了护照，还需要别的吗？", "méi", "một", "không, chưa" },
            new string[] { "米饭", "我不想吃了，刚才吃了很多米饭。", "mǐ fàn", "mễ phạn", "cơm" },
            new string[] { "名字", "右边那个最大的，蓝色的，上面有我的名字。", "míng zì", "danh tự", "tên" },
            new string[] { "明天", "明天是晴天还是阴天？", "míng tiān", "minh thiên", "ngày mai" },
            new string[] { "哪", "女的想看哪个颜色的包？", "nǎ", "ná", "đâu, nào" },
            new string[] { "哪儿", "他们最可能在哪儿？", "nǎr", "ná nhi", "nơi đâu, nơi nào" },
            new string[] { "那", "黑板上的那句话是什么意思？", "nà", "ná", "đó" },
            new string[] { "那儿", "没有，你去图书馆看看，那儿应该有。", "nàr", "ná nhi", "nơi đó, đằng kia" },
            new string[] { "呢", "词典太多了，一共有 50 本呢。", "ne", "ni", "thì sao" },
            new string[] { "能", "谢谢你的关心，我的脚已经好多了，能站起来了。", "néng", "năng", "có thể" },
            new string[] { "你", "不好意思， 我也不太清楚，你问问别人吧。", "nǐ", "nhĩ", "bạn, ông" },
            new string[] { "年", "这几年，我去了很多国家和城市。", "nián", "niên", "năm" },
            new string[] { "女儿", "我只有一个女儿。", "nǚ ér", "nữ nhi", "con gái" },
            new string[] { "朋友", "那是我们邻居的女儿，我女儿的好朋友。", "péng you", "bằng hữu", "bạn bè" },
            new string[] { "漂亮", "你觉得世界上哪儿最漂亮？", "piāo liang", "phiêu lượng", "đẹp đẽ" },
            new string[] { "苹果", "那你把面包和苹果带上，下了课吃。", "píng guǒ", "bình quả", "quả táo" },
            new string[] { "七", "你明天到办公室找我，我在七零七。", "qī", "thất", "số bảy" },
            new string[] { "前面", "眼睛看着前面，慢慢地骑。", "qián miàn", "tiền diện", "phía trước" },
            new string[] { "钱", "三楼还有一个这样的房子，但要贵十几万块钱。", "qián", "tiền", "tiền" },
            new string[] { "请", "请帮我拿一下盘子。", "qǐng", "thỉnh", "mời, xin, nhờ" },
            new string[] { "去", "他周末上午经常去踢足球。", "qù", "khứ", "đi" },
            new string[] { "热", "这边太热了，我们去树下坐一会儿吧。", "rè", "nhiệt", "nóng" },
            new string[] { "人", "看报纸的人也少了， 大家更愿意看电子书。", "rén", "nhân", "con người" },
            new string[] { "认识", "他以前就认识李医生。", "rèn shi", "nhận thức", "quen biết" },
            new string[] { "日", "我们周日去看看怎么样？", "rì", "nhật", "ngày" },
            new string[] { "三", "你们三个太像了，要认出来还真有点儿难。", "sān", "tam", "số ba" },
            new string[] { "商店", "这是我昨天去商店给妹妹买的生日礼物。", "shāng diàn", "thương điếm", "cửa hàng" },
            new string[] { "上", "黑板上的那句话是什么意思？", "shàng", "thượng", "lên, trên" },
            new string[] { "上午", "他周末上午经常去踢足球。", "shàng wǔ", "thượng ngọ", "buổi sáng" },
            new string[] { "少", "看报纸的人也少了，大家更愿意看电子书。", "shǎo", "thiểu", "thiểu, thiếu, ít" },
            new string[] { "谁", "买这么多鲜花，今天是谁的生日啊？", "shuí", "thùy", "ai" },
            new string[] { "什么", "看什么节目呢？声音这么大！", "shén me", "thập ma", "gì, cái gì" },
            new string[] { "十", "两瓶啤酒，一个笔记本，一共三十块八角五分。", "shí", "thập", "số mười" },
            new string[] { "时候", "问题不大，但你洗脸洗澡的时候要多注意点儿。", "shí hòu", "thời hậu", "khi, lúc" },
            new string[] { "是", "中间这个是我。", "shì", "thị", "là, vâng" },
            new string[] { "书", "上大学时，我喜欢去国家图书馆看书学习。", "shū", "thư", "sách" },
            new string[] { "水", "不需要，回去多喝水，休息两天就好了。", "shuǐ", "thủy", "nước" },
            new string[] { "水果", "那家店的水果蛋糕很好吃，你可以试试。", "shuǐ guǒ", "thủy quả", "trái cây" },
            new string[] { "睡觉", "那只猫经常在哪儿睡觉？", "shuì jiào", "thụy giác", "ngủ" },
            new string[] { "说话", "她说话的声音多好听啊！", "shuō huà", "thuyết thoại", "nói chuyện" },
            new string[] { "四", "我骑了四个月了，一共瘦了六斤。", "sì", "tứ", "số bốn" },
            new string[] { "岁", "从 8 岁起，我每天早上都去跑步， 到现在都 20 年了。", "suì", "tuế", "tuổi" },
            new string[] { "他", "你想想，如果不在电视机前，他会做什么呢？", "tā", "tha", "anh ấy, ông ấy" },
            new string[] { "她", "她很漂亮。", "tā", "tha", "cô ấy, bà ấy" },
            new string[] { "太", "小李，这是你选的马？也太矮了吧。", "tài", "thái", "quá" },
            new string[] { "天气", "今天天气真好，我们去爬山吧？", "tiān qì", "thiên khí", "thời tiết" },
            new string[] { "听", "听说它还很聪明呢，会学人说话。", "tīng", "thính", "nghe" },
            new string[] { "同学", "同学们都很喜欢他。", "tóng xué", "đồng học", "bạn học" },
            new string[] { "喂", "喂，请问张经理在吗", "wèi", "úy", "ê, alô" },
            new string[] { "我", "我九点前必须回到办公室，经理有事情找我，再见。", "wǒ", "ngã", "tôi" },
            new string[] { "我们", "你把我们在北京玩儿的照片发给我吧？", "wǒ men", "ngã môn", "chúng tôi" },
            new string[] { "五", "两瓶啤酒，一个笔记本，一共三十块八角五分。", "wǔ", "ngũ", "số năm" },
            new string[] { "喜欢", "上大学时，我喜欢去国家图书馆看书学习。", "xǐ huān", "hỉ hoan", "thích" },
            new string[] { "下", "看看是不是在椅子下面。", "xià", "hạ", "xuống, rơi" },
            new string[] { "下午", "他让我告诉你， 下午两点半在公司会议室开会。", "xià wǔ", "hạ ngọ", "buổi chiều" },
            new string[] { "下雨", "外面又刮风又下雨的，不会影响飞机起飞吧？", "xià yǔ", "hạ vũ", "mưa" },
            new string[] { "先生", "你认识那位先生，是吗？", "xiān shēng", "tiên sinh", "ông, quý ông" },
            new string[] { "现在", "现在，她觉得那是一件非常快乐的事情。", "xiàn zài", "hiện tại", "hiện tại" },
            new string[] { "想", "今天我想早点儿回家。", "xiǎng", "tưởng", "nhớ, muốn" },
            new string[] { "小", "他不喜欢小狗。", "xiǎo", "tiểu", "nhỏ" },
            new string[] { "小姐", "小姐，请把您的行李箱打开一下。", "xiǎo jie", "tiểu thư", "cô, chị" },
            new string[] { "些", "你好，我想买些花送给妈妈。", "xiē", "ta", "một số" },
            new string[] { "写", "明天上午我们去看你爷爷，你作业写完了没？", "xiě", "tả", "viết" },
            new string[] { "谢谢", "谢谢。 我问您一下， 贵校有多少在读学生？一万？", "xiè xie", "tạ tạ", "cảm ơn" },
            new string[] { "星期", "下个星期六我准备去爬山。", "xīng qī", "tinh kỳ", "thứ, tuần" },
            new string[] { "学生", "你回班里找几个学生帮忙拿一下。", "xué shēng", "học sinh", "học sinh" },
            new string[] { "学习", "上大学时，我喜欢去国家图书馆看书学习。", "xué xí", "học tập", "học tập" },
            new string[] { "学校", "我现在就在学校西门， 但我没找到你说的书店。", "xué xiào", "học hiệu", "trường học" },
            new string[] { "一", "同意， 去年我就跟你说应该换一个新的了。", "yī", "nhất", "số một" },
            new string[] { "衣服", "天气冷，你多穿点儿衣服，小心感冒。", "yī fú", "y phục", "quần áo" },
            new string[] { "医生", "医生，我的手没事吧？", "yī shēng", "y sinh", "bác sĩ" },
            new string[] { "医院", "医院离这儿很远，我们坐出租车去吧。", "yī yuàn", "y viện", "bệnh viện" },
            new string[] { "椅子", "看看是不是在椅子下面。", "yǐ zi", "ỷ tử", "ghế" },
            new string[] { "有", "河上有一条小船。", "yǒu", "hữu", "có" },
            new string[] { "月", "我上个月就搬家了，走路十分钟就到。", "yuè", "nguyệt", "tháng" },
            new string[] { "再见", "再见，一会儿你离开的时候记得关灯。", "zài jiàn", "tái kiến", "tạm biệt" },
            new string[] { "在", "他们最可能在哪儿？", "zài", "tại", "ở, tại, đang" },
            new string[] { "怎么", "我看你都没怎么动筷子，是不是不爱吃羊肉？", "zěn me", "chẩm ma", "sao, làm sao" },
            new string[] { "怎么样", "公司旁边新开的那家蛋糕店怎么样？", "zěn me yàng", "chẩm ma dạng", "như thế nào" },
            new string[] { "这", "我记得他有这本书。", "zhè", "giá", "đây" },
            new string[] { "这儿", "从这儿到那家饭店其实就两站地，我们走过去吧。", "zhèr", "giá nhi", "ở đây, nơi đây" },
            new string[] { "中国", "汉语必须要好，而且要了解中国文化。", "zhōng guó", "trung quốc", "Trung Quốc" },
            new string[] { "中午", "我明天早上的飞机，今天中午有时间见个面吗？", "zhōng wǔ", "trung ngọ", "buổi trưa" },
            new string[] { "住", "他现在住在公司附近。", "zhù", "trú", "sống, ở" },
            new string[] { "桌子", "伞还在桌子上呢，你别忘了。", "zhuō zi", "trác tử", "cái bàn" },
            new string[] { "字", "他的汉字写得很漂亮。", "zì", "tự", "chữ" },
            new string[] { "昨天", "昨天的雨下得非常大，我没带伞。", "zuó tiān", "tạc thiên", "hôm qua" },
            new string[] { "坐", "我们先坐公共汽车，然后换地铁。", "zuò", "tọa", "ngồi" },
            new string[] { "做", "她说长大了要做个音乐老师。", "zuò", "tố", "làm" },
            new string[] { "吧", "外面又刮风又下雨的，不会影响飞机起飞吧？", "ba", "ba", "nhé, nhỉ, nha" },
            new string[] { "白", "我想穿裙子，这条白色的怎么样？", "bái", "bạch", "màu trắng, uổng công" },
            new string[] { "百", "你再向南走两百米就能看到了，我就在书店门口等你。", "bǎi", "bách", "hàng trăm" },
            new string[] { "帮助", "后来在马老师的帮助下，水平才有了很大提高。", "bāng zhù", "bang trợ", "giúp đỡ" },
            new string[] { "报纸", "看报纸的人也少了，大家更愿意看电子书。", "bào zhǐ", "báo chỉ", "báo chí" },
            new string[] { "比", "晴天，比今天冷。", "bǐ", "tỉ", "so sánh" },
            new string[] { "别", "爸爸，我有点儿害怕，我骑上车以后你也别走啊。", "bié", "biệt", "đừng" },
            new string[] { "长", "你的头发太长了，像草一样。", "cháng", "trường", "dài" },//
            new string[] { "唱歌", "明天下午你去唱歌吗", "chàng gē", "xướng ca", "ca hát" },
            new string[] { "出", "我现在出去买吧", "chū", "xuất", "ra" },
            new string[] { "穿", "你多穿件儿衣服，外面阴天，可能会下雨", "chuān", "xuyên", "mặc" },
            new string[] { "船", "我一个朋友明天要来，船七点就到", "chuán", "thuyền", "thuyền, tàu" },
            new string[] { "次", "再见，欢迎您下次再来", "cì", "thứ", "lần" },
            new string[] { "从", "我们从小就认识，到现在都二十多年了", "cóng", "tòng", "từ" },
            new string[] { "错", "对不起，我错了", "cuò", "thác", "sai, nhầm" },
            new string[] { "打篮球", "打篮球怎么样", "dǎ lán qiú", "đả lam cầu", "chơi bóng rổ" },
            new string[] { "大家", "他们的汉语都非常好，大家很喜欢他们", "dà jiā", "đại gia", "mọi người" },
            new string[] { "但是", "我想去，但是我明天下午有课", "dàn shì", "đãn thị" , "nhưng" },
            new string[] { "到", "后面，最右边的是我，找到了吗", "dào", "đáo", "đến" },
            new string[] { "得", "再来点儿米饭吧，你吃得太少了，好的，你也吃", "de", "đắc", "(bổ ngữ)" },
            new string[] { "等", "我在公共汽车上呢，你再等我几分钟", "děng", "đẳng", "chờ, đợi" },
            new string[] { "弟弟", "哪个是你弟弟", "dì di", "đệ đệ", "em trai" },
            new string[] { "第一", "您是第一次来我们这儿吗", "dì yī", "đệ nhất", "thứ nhất" },
            new string[] { "懂", "我不知道怎么做，我没听懂", "dǒng", "đổng", "hiểu" },
            new string[] { "对", "先生，您对这件事情怎么看", "duì", "đối", "đúng, đối với" },
            new string[] { "房间", "您看这个房间怎么样", "fáng jiān", "phòng gian", "phòng" },
            new string[] { "非常", "我觉得非常好", "fēi cháng", "phi thường", "vô cùng" },
            new string[] { "服务员", "服务员，请给我来一杯咖啡", "fú wù yuán", "phục vụ viên", "nhân viên phục vụ" },
            new string[] { "高", "这个椅子怎么样，颜色很好，但是，它太高了", "gāo", "cao", "cao" },
            new string[] { "告诉", "告诉我，哪个最漂亮", "gào sù", "cáo tố", "nói cho biết" },
            new string[] { "哥哥", "你哥哥做什么作", "gē ge", "ca ca", "anh trai" },
            new string[] { "给", "这是他给妻子买的", "gěi", "cấp", "cho" },
            new string[] { "公共汽车", "我在公共汽车上呢，你再等我几分钟", "gōng gòng qì chē", "công cộng hơi xa", "xe buýt" },
            new string[] { "公斤", "我现在七十公斤了", "gōng jīn", "công cân", "kilogram" },
            new string[] { "公司", "你是什么时候来这个公司的", "gōng sī", "công ti", "công ty" },
            new string[] { "贵", "这个椅子有点儿贵，但是颜色好不错", "guì", "quý", "mắc, đắc" },
            new string[] { "过", "去年九月我来过一次", "guò", "qua", "đón (Tết), ăn (sinh nhật), từng, đã từng" },
            new string[] { "还", "你妹妹现在还住在学校里", "hái", "hoàn", "vẫn, còn" },
            new string[] { "孩子", "找到了，你旁边那个女孩子是谁", "hái zi", "hài tử", "trẻ con" },
            new string[] { "好吃", "今天晚上给我准备什么好吃的了", "hǎo chī", "hảo xích", "ngon" },
            new string[] { "号", "十四号的已经卖完了", "hào", "hiệu", "ngày, số" },
            new string[] { "黑", "王小姐的猫是黑色的", "hēi", "hắc", "màu đen" },
            new string[] { "红", "左边那个红色的是我的", "hóng", "hồng", "màu đỏ" },
            new string[] { "欢迎", "再见，欢迎您下次再来", "huān yíng", "hoan nghênh", "hoan nghênh" },
            new string[] { "回答", "谁来回答这个问题", "huí dá", "hồi đáp", "trả lời" },
            new string[] { "机场", "我们再有五分钟就到机场了", "jī chǎng", "cơ trường", "sân bay" },
            new string[] { "鸡蛋", "女儿让我回家的时候买些鸡蛋", "jī dàn", "kê đản", "trứng gà" },
            new string[] { "件", "这几件怎么样，你试一试，好，我喜欢这个颜色的", "jiàn", "kiện", "cái, chiếc" },
            new string[] { "教室", "他还在教室里学习", "jiào shì", "giáo thất", "phòng học" },
            new string[] { "姐姐", "你姐姐真漂亮，我给她介绍个男朋友吧", "jiě jie", "thư thư", "chị gái" },
            new string[] { "介绍", "你姐姐真漂亮，我给她介绍个男朋友吧", "jiè shao", "giới thiệu", "giới thiệu" },
            new string[] { "进", "听说今年有八百多人考进我们学校", "jìn", "tiến", "tiến vào" },
            new string[] { "近", "她住学校里，上班很近", "jìn", "cận", "gần" },
            new string[] { "就", "我不睡了，现在就起", "jiù", "tựu", "thì, liền" },
            new string[] { "觉得", "我觉得非常好", "jué de", "giác đắc", "cảm thấy" },
            new string[] { "咖啡", "服务员，请给我来一杯咖啡", "kā fēi", "ca phi", "cà phê" },
            new string[] { "开始", "别说话，电影要开始了", "kāi shǐ", "khai thỉ", "bắt đầu" },
            new string[] { "考试", "听力考试现在开始", "kǎo shì", "khảo thức", "thi cử" },
            new string[] { "可能", "你多穿件儿衣服，外面阴天，可能会下雨", "kě néng", "khả năng", "có lẽ" },
            new string[] { "可以", "听和说还可以，读和写不好", "kě yǐ", "khả dĩ", "có thể" },
            new string[] { "课", "我想去，但是我明天下午有课", "kè", "khóa", "bài" },
            new string[] { "快", "张小姐的飞机快到了，我们还要多长时间", "kuài", "khoái", "nhanh" },
            new string[] { "快乐", "生日快乐，这是我送给你的", "kuài lè", "khoái lạc", "vui vẻ" },
            new string[] { "累", "没关系，我不累", "lèi", "lụy", "mệt" },
            new string[] { "离", "你家离学校远吗", "lí", "li", "cách" },
            new string[] { "两", "我买两斤", "liǎng", "lưỡng", "hai" },
            new string[] { "路", "外面正在下雪，您路上慢点儿", "lù", "lộ", "con đường" },
            new string[] { "旅游", "我想去北京旅游，北京哪儿最好玩儿", "lǚ yóu", "lữ du", "du ngoạn, du lịch" },
            new string[] { "卖", "十四号的已经卖完了", "mài", "mại", "bán" },
            new string[] { "慢", "我的手表慢了", "màn", "mạn", "chậm" },
            new string[] { "忙", "我现在很忙，你五分钟后再打，好吗", "máng", "mang", "bận rộn" },
            new string[] { "每", "他们四个人每天都一起吃饭", "měi", "mỗi", "mỗi" },
            new string[] { "妹妹", "你妹妹现在还住在学校里", "mèi mei", "muội muội", "em gái" },
            new string[] { "门", "谁在门外，是你妈妈回来了，不是，是送牛奶的", "mén", "môn", "môn, cửa" },
            new string[] { "男人", "那个男人是老师", "nán rén", "nam nhân", "đàn ông" },
            new string[] { "您", "再见，欢迎您下次再来", "nín", "nhẫm", "ngài, quý ông" },
            new string[] { "牛奶", "谁在门外，是你妈妈回来了，不是，是送牛奶的", "niú nǎi", "ngưu nãi", "sữa bò" },
            new string[] { "女人", "那个女人是学生", "nǚ rén", "nữ nhân", "phụ nữ" },
            new string[] { "旁边", "找到了，你旁边那个女孩子是谁", "páng biān", "bàng biên", "kế bên" },
            new string[] { "跑步", "那我们明天去跑步吧", "pǎo bù", "bão bộ", "chạy bộ" },
            new string[] { "便宜", "鱼真便宜，现在三块钱一斤了", "pián yi", "tiện nghi", "rẻ tiền" },
            new string[] { "票", "这是李小姐的电影票，你能帮我给她吗", "piào", "phiếu", "vé" },
            new string[] { "妻子", "这是他给妻子买的", "qī zi", "thê tử", "vợ" },
            new string[] { "起床", "今天你准备几点起床", "qǐ chuáng", "khởi sàng", "thức dậy" },
            new string[] { "千", "学生有两千多人", "qiān", "thiên", "hàng ngàn" },
            new string[] { "晴", "雨不下了，天晴了", "qíng", "tinh", "ngày nắng" },
            new string[] { "去年", "去年九月我来过一次", "qù nián", "khứ niên", "năm ngoái" },
            new string[] { "让", "女儿让我回家的时候买些鸡蛋", "ràng", "nhượng", "để, bị, được" },
            new string[] { "上班", "她住学校里，上班很近", "shàng bān", "thượng ban", "vào ca" },
            new string[] { "身体", "吃药了吗，现在身体怎么样", "shēn tǐ", "thân thể", "cơ thể, sức khỏe" },
            new string[] { "生病", "你生病了，要多喝水，多休息", "shēng bìng", "sinh bệnh", "bệnh, bị bệnh" },
            new string[] { "生日", "生日快乐，这是我送给你的", "shēng rì", "sinh nhật", "sinh nhật" },
            new string[] { "时间", "你学汉语多长时间了", "shí jiān", "thời gian", "thời gian" },
            new string[] { "事情", "今天要做的事情真多", "shì qíng", "sự tình", "sự việc" },
            new string[] { "手表", "我的手表慢了", "shǒu biǎo", "thủ biểu", "đồng hồ đeo tay" },
            new string[] { "手机", "你看见我的手机了吗", "shǒu jī", "thủ cơ", "điện thoại di động" },
            new string[] { "送", "生日快乐，这是我送给你的", "sòng", "tống", "tặng, tiễn" },
            new string[] { "所以", "他这次没考好，所以不高兴", "suǒ yǐ", "sở dĩ", "cho nên" },
            new string[] { "它", "这个椅子怎么样，颜色很好，但是，它太高了", "tā", "tha", "nó" },
            new string[] { "踢足球", "我最喜欢踢足球", "tī zú qiú", "thích túc cầu", "đá bóng" },
            new string[] { "跳舞", "她正在学习跳舞，每星期上一次课", "tiào wǔ", "khiêu vũ", "nhảy múa" },
            new string[] { "题", "很多题我都不会做", "tí", "đề", "đề, câu" },
            new string[] { "完", "十四号的已经卖完了", "wán", "hoàn", "xong" },
            new string[] { "外", "你多穿件儿衣服，外面阴天，可能会下雨", "wài", "ngoại", "ngoài" },
            new string[] { "晚上", "您儿子打了个电话，问您晚上在哪儿吃饭", "wǎn shàng", "vãn thượng", "buổi tối" },
            new string[] { "玩", "我想去北京旅游，北京哪儿最好玩儿", "wán", "ngoạn", "chơi" },
            new string[] { "问", "您儿子打了个电话，问您晚上在哪儿吃饭", "wèn", "vấn", "hỏi" },
            new string[] { "为什么", "他们今天为什么不去小张吗", "wèi shén me", "vi thập ma", "tại sao" },
            new string[] { "问题", "谁来回答这个问题", "wèn tí", "vấn đề", "vấn đề, câu hỏi" },
            new string[] { "希望", "我希望她能和您学跳舞，可以吗", "xī wàng", "hi vọng", "hi vọng" },
            new string[] { "西瓜", "天气太热了，家里有西瓜吗", "xī guā", "tây qua", "dưa hấu" },
            new string[] { "向", "到了前面再向右走", "xiàng", "hướng", "hướng" },
            new string[] { "洗", "我去洗洗手", "xǐ", "tẩy", "rửa, giặt" },
            new string[] { "笑", "她笑着说，明天见", "xiào", "tiếu", "cười" },
            new string[] { "小时", "还不到九点呢，我们早来了一个小时", "xiǎo shí", "tiểu thời", "giờ, tiếng đồng hồ" },
            new string[] { "姓", "你好，我姓张，你可以叫我小张", "xìng", "tính", "họ" },
            new string[] { "新", "公司前面新开了一家饭店，你去过吗", "xīn", "tân", "mới" },
            new string[] { "雪", "外面正在下雪，您路上慢点儿", "xuě", "tuyết", "tuyết" },
            new string[] { "休息", "你眼睛怎么这么红，没休息好", "xiū xī", "hưu tức", "nghỉ ngơi" },
            new string[] { "眼睛", "你眼睛怎么这么红，没休息好", "yǎn jīng", "nhãn tinh", "con mắt" },
            new string[] { "颜色", "这几件怎么样，你试一试，好，我喜欢这个颜色的", "yán sè", "nhan sắc", "màu sắc" },
            new string[] { "药", "没什么大问题，我给你开点儿药，回去好好休息", "yào", "dược", "thuốc" },
            new string[] { "羊肉", "今天的羊肉做得很好吃，你怎么不吃了", "yáng ròu", "dương nhục", "thịt dê" },
            new string[] { "也", "再来点儿米饭吧，你吃得太少了，好的，你也吃", "yě", "dã", "cũng" },
            new string[] { "要", "今天要做的事情真多", "yào", "yếu", "muốn, phải" },
            new string[] { "一起", "他们四个人每天都一起吃饭", "yī qǐ", "nhất khởi", "cùng nhau" },
            new string[] { "已经", "十四号的已经卖完了", "yǐ jīng", "dĩ kinh", "đã" },
            new string[] { "阴", "你多穿件儿衣服，外面阴天，可能会下雨", "yīn", "âm", "âm u" },
            new string[] { "意思", "男的是什么意思", "yì sī", "ý tư", "ý nghĩa" },
            new string[] { "游泳", "我上个星期已经看过了，我们去游泳吧", "yóu yǒng", "du vịnh", "bơi lội" },
            new string[] { "因为", "因为明天要早起", "yīn wèi", "nhân vị", "bởi vì" },
            new string[] { "鱼", "鱼真便宜，现在三块钱一斤了", "yú", "ngư", "con cá" },
            new string[] { "右边", "后面，最右边的是我，找到了吗", "yòu biān", "hữu biên", "bên phải" },
            new string[] { "远", "你家离学校远吗", "yuǎn", "viễn", "xa" },
            new string[] { "元", "那个手机不到一千元", "yuán", "nguyên", "đồng, tệ" },
            new string[] { "再", "再见，欢迎您下次再来", "zài", "tái", "lại, lần nữa" },
            new string[] { "运动", "你喜欢什么运动", "yùn dòng", "vận động", "thể thao" },
            new string[] { "张", "你好，我姓张，你可以叫我小张", "zhāng", "trương", "tờ, họ Trương" },
            new string[] { "早上", "是今天早上的报纸吗", "zǎo shàng", "tảo thượng", "buổi sáng sớm" },
            new string[] { "找", "后面，最右边的是我，找到了吗", "zhǎo", "trảo", "tìm, kiếm" },
            new string[] { "丈夫", "我来介绍一下，这是我丈夫", "zhàng fū", "trượng phu", "chồng" },
            new string[] { "真", "今天要做的事情真多", "zhēn", "chân", "thật" },
            new string[] { "着", "他们开着车出去了", "zhe", "trước", "đang, có" },
            new string[] { "知道", "你知道你们学校有多少学生吗", "zhī dào", "tri đạo", "biết" },
            new string[] { "正在", "他回来的时候，我正在洗衣服呢", "zhèng zài", "chính tại", "đang" },
            new string[] { "自行车", "我在门外看到他的自行车了", "zì xíng chē", "tự hành xa", "xe đạp" },
            new string[] { "准备", "今天你准备几点起床", "zhǔn bèi", "chuẩn bị", "chuẩn bị" },
            new string[] { "最", "我最喜欢踢足球", "zuì", "tối", "nhất" },
            new string[] { "走", "爸爸，你别走", "zǒu", "tẩu", "đi" },
            new string[] { "左边", "左边那个红色的是我的", "zuǒ biān", "tả biên", "bên trái" },
            new string[] { "阿姨", "晚上陈阿姨要来家里", "ā yí", "a di", "dì, thím"},
            new string[] { "啊", "刚才天气多好啊", "a", "a", "a, hả, ư..."},
            new string[] { "矮", "儿子比爸爸矮。", "ǎi", "oải", "ngắn, lùn"},
            new string[] { "爱好", "他有很多爱好，唱歌、 画画儿、 踢足球、 玩儿音乐，什么都会，而且水平也都特别高", "ài hǎo", "ái hảo", "sở thích"},
            new string[] { "安静", "真奇怪，动物园里今天怎么这么安静？", "ān jìng", "an tĩnh", "yên tĩnh"},
            new string[] { "把", "你等一下，我去把电视的声音关小一些。", "bǎ", "bả", "đem (nghĩa ngữ pháp)"},
            new string[] { "班", "其他班的成绩也有很大提高。", "bān", "ban", "lớp, ca"},
            new string[] { "搬", "我终于有了自己的大房子了，明天就可以搬家了。", "bān", "ban", "khiêng, dọn"},
            new string[] { "半", "您来早了一点儿，现在才八点半。", "bàn", "bán", "nửa, rưỡi"},
            new string[] { "办法", "没办法，我只能站在外面等休息时间。", "bàn fǎ", "biện pháp", "biện pháp"},
            new string[] { "办公室", "我九点前必须回到办公室，经理有事情找我，再见。", "bàn gōng shì", "ban công thất", "văn phòng"},
            new string[] { "帮忙", "太好了！需要我帮忙吗？", "bāng máng", "", "giúp đỡ"},
            new string[] { "包", "这个包是今年冬天新出的，卖得非常好。", "bāo", "bao", "túi xách"},
            new string[] { "饱", "我已经饱了，不想吃米饭了。", "bǎo", "bão", "no"},
            new string[] { "北方", "北方的秋天就是这样的。", "běi fāng", "bắc phương", "miền Bắc"},
            new string[] { "被", "它为什么被叫做“九日山”？", "bèi", "bị", "bị, được"},
            new string[] { "鼻子", "家里人一般觉得我的鼻子和耳朵像我爸爸，眼睛像我妈妈。", "bí zi", "tị tử", "mũi"},
            new string[] { "比较", "上午的考试比较简单。", "bǐ jiào", "tỉ giảo", "tương đối"},
            new string[] { "比赛", "等一会儿，比赛还有三分钟就结束了。", "bǐ sài", "tỉ trại", "thi đua"},
            new string[] { "必须", "我九点前必须回到办公室，经理有事情找我，再见。", "bì xū", "tất tu", "cần thiết"},
            new string[] { "变化", "我去年春节去过一次上海，今年再去的时候，发现那里的变化非常大。", "biàn huà", "biến hóa", "thay đổi, biến hóa"},
            new string[] { "表示", "天短了表示什么意思？", "biǎo shì", "biểu thị", "biểu thị"},
            new string[] { "表演", "小姐，请问表演什么时候开始？", "biǎo yǎn", "biểu diễn", "biểu diễn"},
            new string[] { "别人", "邻居是一位年轻的医生，他很热情，喜欢帮助别人，所以大家有什么问题，都愿意请他帮忙。", "bié ren", "biệt nhân", "người khác"},
            new string[] { "宾馆", "宾馆旁边有个公园。", "bīn guǎn", "tân quán", "khách sạn"},
            new string[] { "冰箱", "这个冰箱太旧了，我们买个新的吧。", "bīng xiāng", "băng tương", "tủ lạnh"},
            new string[] { "菜单", "把菜单儿给我，我们喝杯绿茶吧？", "cài dān", "thái đơn", "thực đơn"},
            new string[] { "才", "他去旅游了，可能这个周末才能回来。", "cái", "tài", "mới"},
            new string[] { "草", "那里有草地，有大树，还有鸟", "cǎo", "thảo", "cỏ"},
            new string[] { "参加", "您是来参加今天会议的吗？", "cān jiā", "tham gia", "tham gia"},
            new string[] { "差", "昨天晚上睡得太晚，今天起床时已经 8 点多了，我刷了牙，洗了脸，就出来了，差点儿忘了关门。", "chà", "sai", "kém"},
            new string[] { "层", "当然可以，我先看一下您的票，好，您向左走，坐电梯上二层。", "céng", "tầng", "tầng"},
            new string[] { "衬衫", "你看看，在你自己的衬衫里呢。", "chèn shān", "sấn sam", "áo sơ mi"},
            new string[] { "超市", "没问题。您去超市了？", "chāo shì", "siêu thị", "siêu thị"},
            new string[] { "城市", "这个城市的环境变得越来越好了。", "chéng shì", "thành thị", "thành phố"},
            new string[] { "成绩", "其他班的成绩也有很大提高。", "chéng jì", "thành tích", "thành tích"},
            new string[] { "出现", "你看，上次出现的问题，我已经解决了。", "chū xiàn", "xuất hiện", "xuất hiện"},
            new string[] { "迟到", "你总是这么慢，快 7 点了，要迟到了。", "chí dào", "trì đáo", "đến trễ"},
            new string[] { "除了", "每次坐火车前，周明都会去超市买一些东西，除了面包、水果，他还要买一些报纸。", "chú le", "trừ liễu", "ngoài ra, ngoại trừ"},
            new string[] { "厨房", "你家的厨房真干净！", "chú fáng", "trù phòng", "nhà bếp"},
            new string[] { "春", "我去年春节去过一次上海，今年再去的时候，发现那里的变化非常大。", "chūn", "xuân", "mùa xuân"},
            new string[] { "词语", "请大家把黑板上的这些词写在本子上，回家后用这些词语写一个小故事，别忘了，最少写 100 字。", "cí yǔ", "từ ngữ", "từ ngữ"},
            new string[] { "聪明", "对一个女人来说，漂亮、 聪明都很重要", "cōng ming", "thông minh", "thông minh"},
            new string[] { "打算", "他们打算在哪儿见面？", "dǎ suàn", "đả toán", "dự định"},
            new string[] { "打扫", "终于把教室打扫干净了，她洗澡去了。", "dǎ sǎo", "đả tảo", "quét dọn"},
            new string[] { "担心", "没事，不用担心。就是感冒发烧，很快就会好的。", "dān xīn", "đảm tâm", "lo lắng"},
            new string[] { "带", "昨天的雨下得非常大，我没带伞。", "dài", "đái", "mang, dẫn"},
            new string[] { "当然", "当然可以，我先看一下您的票，好，您向左走，坐电梯上二层。", "dāng rán", "đương nhiên", "đương nhiên"},
            new string[] { "蛋糕", "小孩子爱吃蛋糕。", "dàn gāo", "đản cao", "bánh bông lan"},
            new string[] { "地", "弟弟高兴地笑了。", "de", "địa", "(trạng ngữ)"},
            new string[] { "灯", "服务员，我房间里的灯坏了。", "dēng", "đăng", "đèn"},
            new string[] { "地方", "他在北京玩了很多地方。", "dì fang", "địa phương", "nơi chốn"},
            new string[] { "低", "他很高，这张桌子太低", "dī", "đê", "thấp"},
            new string[] { "地图", "眼镜，帽子，地图，啤酒，一个也不能少。", "dì tú", "địa đồ", "bản đồ"},
            new string[] { "地铁", "当然。我们先坐公共汽车，然后换地铁。", "dì tiě", "địa thiết", "tàu điện ngầm"},
            new string[] { "电子邮件", "她每天到办公室的第一件事就是打开电脑，看电子邮件，然后才开始别的工作。", "diàn zǐ yóu jiàn", "điện tử bưu kiện", "e-mail"},
            new string[] { "电梯", "当然可以，我先看一下您的票，好，您向左走，坐电梯上二层。", "diàn tī", "điện thê", "thang máy"},
            new string[] { "冬", "虽然冬天天气很冷，但是空气新鲜，而且房间里一点儿也不冷。", "dōng", "đông", "mùa đông"},
            new string[] { "东", "李阿姨是东北人，她说东北的冬天比南方冷多了，而且还经常下雪。", "dōng", "đông", "(hướng) đông"},
            new string[] { "动物", "真奇怪，动物园里今天怎么这么安静？", "dòng wù", "động vật", "động vật"},
            new string[] { "短", "现在天“短”了。", "duǎn", "đoản", "ngắn"},
            new string[] { "段", "你看看这段话这样写怎么样？", "duàn", "đoạn", "đoạn"},
            new string[] { "锻炼", "为了让自己更健康，他每天都花一个小时去锻炼身体。", "duàn liàn", "đoàn luyện", "rèn luyện"},
            new string[] { "多么", "这是一个多么好的机会啊！你必须去。", "duō me", "đa ma", "biết bao"},
            new string[] { "饿", "今天把我饿坏了，还有什么吃的吗？", "è", "ngạ", "đói"},
            new string[] { "而且", "虽然冬天天气很冷，但是空气新鲜，而且房间里一点儿也不冷。", "ér qiě", "nhi thả", "mà, mà còn"},
            new string[] { "耳朵", "家里人一般觉得我的鼻子和耳朵像我爸爸，眼睛像我妈妈。", "ěr duo", "nhĩ đóa", "lỗ tai"},
            new string[] { "发现", "我去年春节去过一次上海，今年再去的时候，发现那里的变化非常大。", "fā xiàn", "phát hiện", "phát hiện"},
            new string[] { "发烧", "就是感冒发烧，很快就会好的。", "fā shāo", "phát thiêu", "nóng sốt"},
            new string[] { "放", "没有啊，只有我的。你的放哪儿了？", "fàng", "phóng", "thả, đặt"},
            new string[] { "方便", "环境是不错，买东西也方便，附近就有超市，就是离地铁远。", "fāng biàn", "phương tiện", "tiện lợi"},
            new string[] { "放心", "没问题，你就放心吧。", "fàng xīn", "phóng tâm", "yên tâm"},
            new string[] { "复习", "把电视声音关小点儿，你弟弟明天考试，正在复习呢，别影响他。", "fù xí", "phục tập", "ôn tập"},
            new string[] { "附近", "环境是不错，买东西也方便，附近就有超市，就是离地铁远。", "fù jìn", "phụ cận", "gần đây"},
            new string[] { "敢", "我看你明天敢不敢穿。", "gǎn", "cảm", "dám"},
            new string[] { "干净", "你家的厨房真干净！", "gān jìng", "can tịnh", "sạch sẽ"},
            new string[] { "感冒", "就是感冒发烧，很快就会好的。", "gǎn mào", "cảm mạo", "cảm mạo"},
            new string[] { "刚才", "刚才天气多好啊，突然就刮起大风了。", "gāng cái", "cương tài", "hồi nãy"},
            new string[] { "根据", "根据这段话，可以知道什么？", "gēn jù", "căn cứ", "căn cứ theo"},
            new string[] { "跟", "同意，去年我就跟你说应该换一个新的了。", "gēn", "cân", "theo, với"},
            new string[] { "更", "那祝你在新的一年里学习更上一层楼。", "gēng", "canh", "càng"},
            new string[] { "公园", "宾馆旁边有个公园。", "gōng yuán", "công viên", "công viên"},
            new string[] { "故事", "请大家把黑板上的这些词写在本子上，回家后用这些词语写一个小故事，别忘了，最少写 100 字。", "gù shi", "cố sự", "câu chuyện"},
            new string[] { "刮风", "也刮风，但没有这么大。", "guā fēng", "quát phong", "nổi gió"},
            new string[] { "关", "那家药店晚上几点关门？", "guān", "quan", "đóng, tắt"},
            new string[] { "关心", "大家都很关心您的身体，现在好些了吗？", "guān xīn", "quan tâm", "quan tâm"},
            new string[] { "关系", "说话人最可能是什么关系？", "guān xi", "quan hệ", "quan hệ"},
            new string[] { "关于", "关于表演，下面哪个是对的？", "guān yú", "quan vu", "về (cái gì, điều gì)"},
            new string[] { "过去", "好久没见面，我们就在公司旁边那个咖啡馆里坐了坐，一边喝咖啡一边说了些过去的事，所以回来晚了。", "guò qu", "quá khứ", "quá khứ"},
            new string[] { "国家", "这次比赛，世界很多国家的运动员都来参加。", "guó jiā", "quốc gia", "quốc gia"},
            new string[] { "果汁", "晚上开车，来杯茶或者苹果汁吧。", "guǒ zhī", "quả trấp", "nước ép trái cây"},
            new string[] { "害怕", "有些人不喜欢吃蛋糕，是因为害怕长胖。", "hài pà", "hại phạ", "sợ hãi"},
            new string[] { "还是", "那还是我做饭吧，我愿意做饭。", "hái shì", "hoàn thị", "hay là, vẫn là"},
            new string[] { "河", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "hé", "hà", "sông"},
            new string[] { "黑板", "请大家把黑板上的这些词写在本子上，回家后用这些词语写一个小故事，别忘了，最少写 100 字。", "hēi bǎn", "hắc bản", "bảng đen"},
            new string[] { "护照", "我的护照在你包里吗？", "hù zhào", "hộ chiếu", "hộ chiếu"},
            new string[] { "花", "为了让自己更健康，他每天都花一个小时去锻炼身体。", "huā", "hoa", "tốn, tiêu"},
            new string[] { "花园", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "huā yuán", "hoa viên", "vườn hoa"},
            new string[] { "画", "他有很多爱好，唱歌、 画画儿、 踢足球、 玩儿音乐，什么都会，而且水平也都特别高。", "huà", "họa", "tranh, vẽ"},
            new string[] { "坏", "服务员，我房间里的灯坏了。", "huài", "hoại", "xấu, hỏng"},
            new string[] { "还", "我已经从图书馆出来了，那几本书都还了，你们等我一会儿，我很快就到。", "huán", "hoàn", "hoàn trả", "环"},
            new string[] { "环境", "这个城市的环境变得越来越好了。", "huán jìng", "hoàn cảnh", "môi trường"},
            new string[] { "换", "当然。我们先坐公共汽车，然后换地铁。", "huàn", "hoán", "đổi"},
            new string[] { "黄", "你不知道？儿子昨天买了两只小鸟，一只红色的，一只黄色的。", "huáng", "hoàng", "màu vàng"},
            new string[] { "或者", "给他一块儿糖，或者和他做游戏。", "huò zhě", "hoặc giả", "có lẽ, có thể, hoặc là (liên từ)"},
            new string[] { "会议", "如果我不在，你就上八楼，到八零三会议室找我，我可能在那儿开会。", "huì yì", "hội nghị", "hội nghị"},
            new string[] { "机会", "我这次来北京，只能住三天，所以我只能选择一两个最有名的地方去看看，以后有机会再去别的地方。", "jī huì", "cơ hội", "cơ hội"},
            new string[] { "几乎", "经过那条街道时，我几乎不认识了。", "jǐ hū", "kỷ hồ", "hầu như, hầu hết"},
            new string[] { "记得", "好极了！只是你要注意身体，我记得你有一个多星期没去跑步了。", "jì de", "kí đắc", "nhớ, nhớ lại"},
            new string[] { "极", "好极了！只是你要注意身体，我记得你有一个多星期没去跑步了。", "jí", "cực", "cực điểm, cực kì, cực độ, hết sức"},
            new string[] { "季节", "你是南方人，你们那儿这个季节怎么样？", "jì jié", "quý tiết", "mùa"},
            new string[] { "简单", "上午的考试比较简单。", "jiǎn dān", "giản đơn", "đơn giản"},
            new string[] { "检查", "你最好再检查一下，看还有没有问题。", "jiǎn chá", "kiểm tra", "kiểm tra"},
            new string[] { "见面", "好久没见面，我们就在公司旁边那个咖啡馆里坐了坐，一边喝咖啡一边说了些过去的事，所以回来晚了。", "jiàn miàn", "kiến diện", "gặp mặt"},
            new string[] { "健康", "为了让自己更健康，他每天都花一个小时去锻炼身体。", "jiàn kāng", "kiện khang", "khỏe mạnh, tráng kiện, sức khỏe"},
            new string[] { "讲", "小刘是一位小学老师，教三年级的数学，他虽然很年轻，但是课讲得很好，同学们都很喜欢他。", "jiǎng", "giảng", "giảng, nói, giải thích"},
            new string[] { "角", "一元是 10 角，一角是 10 分。", "jiǎo", "giác", "hào"},
            new string[] { "教", "我看您对中国历史很了解，您是教历史的吗？", "jiāo", "giáo", "dạy"},
            new string[] { "脚", "休息一下吧，我现在腿也疼，脚也疼。", "jiǎo", "cước", "chân"},
            new string[] { "接", "你在忙什么呢？刚才打你的手机你也不接。", "jiē", "tiếp", "nhận, đón"},
            new string[] { "结婚", "明天同学结婚，我在想穿哪双鞋好呢。", "jié hūn", "kết hôn", "kết hôn"},
            new string[] { "街道", "经过那条街道时，我几乎不认识了。", "jiē dào", "nhai đạo", "đường phố"},
            new string[] { "节目", "告诉我你想看什么节目。", "jié mù", "tiết mục", "tiết mục"},
            new string[] { "结束", "等一会儿，比赛还有三分钟就结束了。", "jié shù", "kết thúc", "kết thúc"},
            new string[] { "解决", "你看，上次出现的问题，我已经解决了。", "jiě jué", "giải quyết", "giải quyết"},
            new string[] { "节日", "她这才明白今天是他们的节日。", "jié rì", "tiết nhật", "ngày lễ"},
            new string[] { "借", "还有一个问题，我可以借几天呢？", "jiè", "tá", "mượn, vay"},
            new string[] { "经理", "喂，请问张经理在吗？", "jīng lǐ", "kinh lí", "giám đốc, quản lý kinh doanh"},
            new string[] { "经常", "那只猫经常在哪儿睡觉？", "jīng cháng", "kinh thường", "thường hay"},
            new string[] { "经过", "经过那条街道时，我几乎不认识了。", "jīng guò", "kinh qua", "trải qua, đi ngang qua"},
            new string[] { "久", "好久没见面，我们就在公司旁边那个咖啡馆里坐了坐，一边喝咖啡一边说了些过去的事，所以回来晚了。", "jiǔ", "cửu", "lâu"},
            new string[] { "旧", "这个冰箱太旧了，我们买个新的吧。", "jiù", "cựu", "cũ"},
            new string[] { "句子", "除了这个句子意思有些不清楚外，其他都不错。", "jù zi", "cú tử", "câu"},
            new string[] { "举行", "这里的香蕉非常有名，每年 8 月这里会举行一个香蕉节，所以，夏季有很多人来这里玩儿。", "jǔ xíng", "cử hành", "tiến hành"},
            new string[] { "决定", "你决定了？ 好，我看你明天敢不敢穿。", "jué dìng", "quyết định", "quyết định"},
            new string[] { "可爱", "这个小孩儿胖胖的，真可爱。", "kě ài", "khả ái", "đáng yêu"},
            new string[] { "渴", "又渴又累，腿也疼。", "kě", "khát", "khát"},
            new string[] { "客人", "客人马上就要来了，你去告诉李小姐先把房间里的空调打开，今天太热了。", "kè rén", "khách nhân", "khách"},
            new string[] { "刻", "我看一下，现在差一刻九点。", "kè", "khắc", "15 phút"},
            new string[] { "空调", "他们在买空调。", "kōng tiáo", "không điều", "máy điều hòa"},
            new string[] { "口", "你再向南走两百米就能看到了，我就在书店门口等你。", "kǒu", "khẩu", "miệng"},
            new string[] { "哭", "他总是哭，有什么办法可以让他不哭吗？", "kū", "khốc", "khóc"},
            new string[] { "裤子", "这条裤子你花了多少钱？", "kù zi", "khố tử", "quần"},
            new string[] { "筷子", "你准备了几双筷子？", "kuài zi", "khoái tử", "đũa"},
            new string[] { "蓝", "好的，谢谢你。那个蓝色的是我的。", "lán", "lam", "màu xanh lam"},
            new string[] { "老", "李老师，您有两个孩子？", "lǎo", "lão", "già"},
            new string[] { "历史", "我看您对中国历史很了解，您是教历史的吗？", "lì shǐ", "lịch sử", "lịch sử"},
            new string[] { "离开", "你这次要离开多长时间？", "lí kāi", "li khai", "rời khỏi"},
            new string[] { "礼物", "那位医生送给他一个礼物。", "lǐ wù", "lễ vật", "quà"},
            new string[] { "练习", "很大，我做练习的时候，它很有帮助。", "liàn xí", "luyện tập", "luyện tập, bài tập"},
            new string[] { "脸", "昨天晚上睡得太晚，今天起床时已经 8 点多了，我刷了牙，洗了脸，就出来了，差点儿忘了关门。", "liǎn", "liễm", "khuôn mặt"},
            new string[] { "辆", "这辆车现在能卖十万块钱吧，我两年前买的时候花了二十多万。", "liàng", "lượng", "chiếc (lượng từ của xe)"},
            new string[] { "了解", "我看您对中国历史很了解，您是教历史的吗？", "liǎo jiě", "liễu giải", "tìm hiểu"},
            new string[] { "邻居", "那是我们邻居的女儿，我女儿的好朋友。", "lín jū", "lân cư", "hàng xóm, láng giềng"},
            new string[] { "楼", "那祝你在新的一年里学习更上一层楼。", "lóu", "lâu", "tòa nhà, lầu"},
            new string[] { "绿", "把菜单儿给我，我们喝杯绿茶吧？", "lǜ", "lục", "màu xanh lá"},
            new string[] { "马", "银行马上就要关门了。", "mǎ", "mã", "con ngựa"},
            new string[] { "马上", "银行马上就要关门了。", "mǎ shàng", "mã thượng", "ngay lập tức"},
            new string[] { "满意", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "mǎn yì", "mãn ý", "hài lòng"},
            new string[] { "帽子", "眼镜，帽子，地图，啤酒，一个也不能少。", "mào zi", "mạo tử", "nón, mũ"},
            new string[] { "米", "你再向南走两百米就能看到了，我就在书店门口等你。", "mǐ", "mễ", "gạo, mét"},
            new string[] { "面条", "你先来个苹果，我去给你做碗面条儿。", "miàn tiáo", "diện điều", "mì"},
            new string[] { "面包", "每次坐火车前，周明都会去超市买一些东西，除了面包、水果，他还要买一些报纸。", "miàn bāo", "diện bao", "bánh mì"},
            new string[] { "明白", "就是说白天的时间短了，天黑的时间早了，明白了？", "míng bai", "minh bạch", "rõ ràng"},
            new string[] { "拿", "再拿两双，你爷爷奶奶一会儿就过来，我们一起吃。", "ná", "nã", "cầm, lấy"},
            new string[] { "奶奶", "再拿两双，你爷爷奶奶一会儿就过来，我们一起吃。", "nǎi nai", "nãi nãi", "bà nội"},
            new string[] { "难", "没关系，别难过，高兴点儿。", "nán", "nan", "khó"},
            new string[] { "南", "你再向南走两百米就能看到了，我就在书店门口等你。", "nán", "nam", "phía nam"},
            new string[] { "难过", "没关系，别难过，高兴点儿。", "nán guò", "nan quá", "buồn bã"},
            new string[] { "年轻", "小刘是一位小学老师，教三年级的数学，他虽然很年轻，但是课讲得很好，同学们都很喜欢他。", "nián qīng", "niên khinh", "trẻ tuổi, thanh niên"},
            new string[] { "年级", "小刘是一位小学老师，教三年级的数学，他虽然很年轻，但是课讲得很好，同学们都很喜欢他。", "nián jí", "niên cấp", "năm thứ"},
            new string[] { "鸟", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "niǎo", "điểu", "chim"},
            new string[] { "努力", "人们常说：今天工作不努力，明天努力找工作。", "nǔ lì", "nỗ lực", "cố gắng"},
            new string[] { "盘子", "我做饭，你洗盘子和碗，怎么样？", "pán zi", "bàn tử", "đĩa, mâm"},
            new string[] { "爬山", "下个星期六我准备去爬山。", "pá shān", "bà sơn", "leo núi"},
            new string[] { "胖", "这个小孩儿胖胖的，真可爱。", "pàng", "bạng", "mập, béo"},
            new string[] { "啤酒", "眼镜，帽子，地图，啤酒，一个也不能少。", "pí jiǔ", "ti tửu", "bia"},
            new string[] { "普通话", "我以前以为北京话就是普通话，到北京两年后，我才发现不是这样的。", "pǔ tōng huà", "phổ thông thoại", "tiếng phổ thông"},
            new string[] { "葡萄", "今天 12 号了，晚上陈阿姨要来家里，家里有菜，有鱼，还有些羊肉，但是没有水果了，你去买些香蕉、葡萄吧，再买个西瓜？", "pú táo", "bồ đào", "quả nho"},
            new string[] { "其他", "其他班的成绩也有很大提高。", "qí tā", "kỳ tha", "cái khác, khác"},
            new string[] { "其实", "我其实对新闻没兴趣，主要是想提高提高我的普通话水平。", "qí shí", "kỳ thực", "thật ra"},
            new string[] { "奇怪", "真奇怪，动物园里今天怎么这么安静？", "qí guài", "kỳ quái", "kì lạ"},
            new string[] { "骑", "你每天都骑自行车上下班？", "qí", "kị", "cưỡi, đạp (xe)"},
            new string[] { "铅笔", "每次下课前，我会把下次学生要带的东西写在黑板上，但每次上课时，总会有学生忘了拿铅笔。", "qiān bǐ", "diên bút", "bút chì"},
            new string[] { "清楚", "姐姐给我买的，我也不太清楚。", "qīng chu", "thanh sở", "rõ ràng"},
            new string[] { "秋", "北方的秋天就是这样的。", "qiū", "thu", "mùa thu"},
            new string[] { "裙子", "那没关系，我不怕冷，我明天要穿我的新裙子。", "qún zi", "quần tử", "chiếc váy"},
            new string[] { "然后", "当然。我们先坐公共汽车，然后换地铁。", "rán hòu", "nhiên hậu", "sau đó"},
            new string[] { "热情", "邻居是一位年轻的医生，他很热情，喜欢帮助别人，所以大家有什么问题，都愿意请他帮忙。", "rè qíng", "nhiệt tình", "nhiệt tình"},
            new string[] { "认真", "好了，准备得很认真，我相信你已经准备好了。", "rèn zhēn", "nhận chân", "cần mẫn, nghiêm túc"},
            new string[] { "认为", "但小孩子看见蛋糕是不会客气的，他们认为蛋糕越甜越好吃。", "rèn wéi", "nhận vi", "cho rằng"},
            new string[] { "容易", "上山容易下山难，你不知道？", "róng yì", "dung dị", "dễ dàng"},
            new string[] { "如果", "如果我不在，你就上八楼，到八零三会议室找我，我可能在那儿开会。", "rú guǒ", "như quả", "nếu"},
            new string[] { "伞", "昨天的雨下得非常大，我没带伞。", "sǎn", "tản", "ô, dù"},
            new string[] { "上网", "这次比赛的新要求和需要注意的一些问题网上都有，你上网看一下，回去跟同学们也说一下。", "shàng wǎng", "thượng võng", "lên mạng"},
            new string[] { "声音", "你等一下，我去把电视的声音关小一些。", "shēng yīn", "thanh âm", "âm thanh"},
            new string[] { "生气", "哥，刘阿姨是不是生气了？", "shēng qì", "sinh khí", "tức giận"},
            new string[] { "使", "手机使我们的学习、工作越来越方便，除了打电话、 写短信外，很多手机还可以照相，有时候真的方便极了。", "shǐ", "sử", "khiến cho, sai bảo"},
            new string[] { "世界", "世界真的很小，我昨天才发现，你给小张介绍的男朋友是我妻子以前的同事。", "shì jiè", "thế giới", "thế giới"},
            new string[] { "瘦", "我骑了四个月了，一共瘦了六斤。", "shòu", "sấu", "ốm, gầy"},
            new string[] { "舒服", "没有啊。 她只是鼻子有点儿不舒服。", "shū fu", "thư phục", "thoải mái"},
            new string[] { "叔叔", "那是我叔叔的儿子，一岁多了。", "shū shu", "thúc thúc", "chú"},
            new string[] { "树", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "shù", "thụ", "cây cối"},
            new string[] { "数学", "小刘是一位小学老师，教三年级的数学，他虽然很年轻，但是课讲得很好，同学们都很喜欢他。", "shù xué", "số học", "toán học"},
            new string[] { "刷牙", "我已经刷牙了。", "shuā yá", "loát nha", "đánh răng"},
            new string[] { "双", "明天同学结婚，我在想穿哪双鞋好呢。", "shuāng", "song", "đôi, cặp"},
            new string[] { "水平", "他有很多爱好，唱歌、 画画儿、 踢足球、 玩儿音乐，什么都会，而且水平也都特别高。", "shuǐ píng", "thủy bình", "trình độ"},
            new string[] { "司机", "我哥是司机，我问问他，看他有没有时间。", "sī jī", "ti cơ", "tài xế"},
            new string[] { "虽然", "我对这儿很满意，虽然没有花园，但是离河边很近，那里有草地，有大树，还有鸟", "suī rán", "tuy nhiên", "tuy"},
            new string[] { "太阳", "太阳从西边出来了吗？", "tài yang", "thái dương", "mặt trời"},
            new string[] { "糖", "给他一块儿糖，或者和他做游戏。", "táng", "đường", "đường, kẹo"},
            new string[] { "特别", "他有很多爱好，唱歌、 画画儿、 踢足球、 玩儿音乐，什么都会，而且水平也都特别高。", "tè bié", "đặc biệt", "đặc biệt"},
            new string[] { "疼", "休息一下吧，我现在腿也疼，脚也疼。", "téng", "đông", "đau, nhức"},
            new string[] { "提高", "其他班的成绩也有很大提高。", "tí gāo", "đề cao", "nâng cao"},
            new string[] { "体育", "我喜欢体育。", "tǐ yù", "thể dục", "thể dục"},
            new string[] { "甜", "有些人不喜欢吃蛋糕，是因为太甜了", "tián", "điềm", "ngọt"},
            new string[] { "条", "这条裤子你花了多少钱？", "tiáo", "điều", "chiếc (lượng từ)"},
            new string[] { "同事", "我的几个同事周末想去北京玩儿，但他们都不会开车。", "tóng shì", "đồng sự", "đồng nghiệp"},
            new string[] { "同意", "同意，去年我就跟你说应该换一个新的了。", "tóng yì", "đồng ý", "đồng ý"},
            new string[] { "头发", "你的头发太长了，像草一样。", "tóu fa", "đầu phát", "tóc"},
            new string[] { "突然", "刚才天气多好啊，突然就刮起大风了。", "tū rán", "đột nhiên", "đột nhiên"},
            new string[] { "图书馆", "我已经从图书馆出来了，那几本书都还了，你们等我一会儿，我很快就到。", "tú shū guǎn", "đồ thư quán", "thư viện"},
            new string[] { "腿", "休息一下吧，我现在腿也疼，脚也疼。", "tuǐ", "thối", "đùi"},
            new string[] { "完成", "我的作业早就完成了。", "wán chéng", "hoàn thành", "hoàn thành"},
            new string[] { "碗", "你先来个苹果，我去给你做碗面条儿。", "wǎn", "uyển", "chén, bát"},
            new string[] { "万", "这辆车现在能卖十万块钱吧，我两年前买的时候花了二十多万。", "wàn", "vạn", "hàng vạn"},
            new string[] { "忘记", "学生会忘记拿什么？", "wàng jì", "vong ký", "quên"},
            new string[] { "为", "这是为老师准备的。", "wèi", "vị", "vì"},
            new string[] { "为了", "为了让自己更健康，他每天都花一个小时去锻炼身体。", "wèi le", "vị liễu", "vì, để"},
            new string[] { "位", "小刘是一位小学老师，教三年级的数学，他虽然很年轻，但是课讲得很好，同学们都很喜欢他。", "wèi", "vị", "vị (lượng từ)"},
            new string[] { "文化", "我们这儿有个西瓜文化节，您有兴趣去看看吗？", "wén huà", "văn hóa", "văn hóa"},
            new string[] { "西", "我现在就在学校西门，但我没找到你说的书店。", "xī", "tây", "hướng tây"},
            new string[] { "习惯", "这儿的冬天就是这样，慢慢地你就习惯了。", "xí guàn", "tập quán", "thói quen, quen"},
            new string[] { "洗手间", "这个房子真的很不错，厨房和洗手间都很大，房子后面还有一个小花园，像您这么喜欢小动物，有个花园会很方便。", "xǐ shǒu jiān", "tẩy thủ gian", "nhà vệ sinh"},
            new string[] { "洗澡", "你敢不敢用冷水洗澡？", "xǐ zǎo", "tẩy tảo", "tắm rửa"},
            new string[] { "夏", "这里的香蕉非常有名，每年 8 月这里会举行一个香蕉节，所以，夏季有很多人来这里玩儿。", "xià", "hạ", "mùa hè"},
            new string[] { "先", "你先吃，我马上就看完了。", "xiān", "tiên", "trước tiên"},
            new string[] { "香蕉", "你去买些香蕉", "xiāng jiāo", "hương tiêu", "quả chuối"},
            new string[] { "相同", "北京话和普通话是相同的。", "xiāng tóng", "tương đồng", "tương đồng"},
            new string[] { "相信", "好了，准备得很认真，我相信你已经准备好了。", "xiāng xìn", "tương tín", "tin tưởng"},
            new string[] { "像", "有人问我长得像谁，这个问题不太好回答。", "xiàng", "tượng", "giống"},
            new string[] { "小心", "西瓜的汁儿多，吃的时候小心点儿，要低下头,不要吃得脸上、 衬衫上都是。还有，不要一边吃一边说话。", "xiǎo xīn", "tiểu tâm", "cẩn thận"},
            new string[] { "校长", "您请坐，王校长正在开会，会议马上就结束了。", "xiào zhǎng", "hiệu trưởng", "hiệu trưởng"},
            new string[] { "鞋", "明天同学结婚，我在想穿哪双鞋好呢。", "xié", "hài", "giày"},
            new string[] { "新闻", "怎么不看新闻了？", "xīn wén", "tân văn", "tin tức thời sự"},
            new string[] { "新鲜", "虽然冬天天气很冷，但是空气新鲜，而且房间里一点儿也不冷。", "xīn xiān", "tân tiên", "tươi mới"},
            new string[] { "信", "好了，准备得很认真，我相信你已经准备好了。", "xìn", "tín", "tin, thư"},
            new string[] { "兴趣", "她对自己的工作没兴趣。", "xìng qù", "hứng thú", "hứng thú"},
            new string[] { "行李箱", "那个行李箱是什么样的？", "xíng li xiāng", "hành lí tương", "va li"},
            new string[] { "熊猫", "大家都在那边儿看新来的大熊猫呢。", "xióng māo", "hùng miêu", "gấu trúc"},
            new string[] { "需要", "太好了！需要我帮忙吗？", "xū yào", "nhu yếu", "cần thiết"},
            new string[] { "选择", "我这次来北京，只能住三天，所以我只能选择一两个最有名的地方去看看，以后有机会再去别的地方。", "xuǎn zé", "tuyển trạch", "lựa chọn"},
            new string[] { "眼镜", "眼镜，帽子，地图，啤酒，一个也不能少。", "yǎn jìng", "nhãn kính", "mắt kính"},
            new string[] { "要求", "这次比赛的新要求和需要注意的一些问题网上都有，你上网看一下，回去跟同学们也说一下。", "yāo qiú", "yêu cầu", "yêu cầu"},
            new string[] { "爷爷", "再拿两双，你爷爷奶奶一会儿就过来，我们一起吃。", "yé ye", "gia gia", "ông nội"},
            new string[] { "一共", "一共 10 个题，每题听两次。", "yī gòng", "nhất cộng", "tổng cộng"},
            new string[] { "一定", "我今天一定能完成作业，相信我好了。", "yī dìng", "nhất định", "nhất định"},
            new string[] { "一样", "你放心，我们家的人都很瘦，吃不胖，我也一样。", "yī yàng", "nhất dạng", "như nhau"},
            new string[] { "一会儿", "过了一会儿再看表，还是五点，我这才发现我的手表不走了。", "yī huì r", "nhất hội nhi", "một chút, một chốc"},
            new string[] { "以前", "我以前以为北京话就是普通话，到北京两年后，我才发现不是这样的。", "yǐ qián", "dĩ tiền", "trước đây"},
            new string[] { "以后", "他正在开会，您半个小时以后再打，好吗？", "yǐ hòu", "dĩ hậu", "sau này"},
            new string[] { "一般", "家里人一般觉得我的鼻子和耳朵像我爸爸，眼睛像我妈妈。", "yī bān", "nhất ban", "thông thường"},
            new string[] { "以为", "我以前以为北京话就是普通话，到北京两年后，我才发现不是这样的。", "yǐ wèi", "dĩ vị", "tưởng rằng"},
            new string[] { "一直", "你一直看手表，有什么着急的事情吗？", "yī zhí", "nhất trực", "mãi, suốt, luôn, liên tục"},
            new string[] { "一边", "好久没见面，我们就在公司旁边那个咖啡馆里坐了坐，一边喝咖啡一边说了些过去的事，所以回来晚了。", "yī biān", "nhất biên", "vừa … vừa …"},
            new string[] { "银行", "银行马上就要关门了。", "yín háng", "ngân hàng", "ngân hàng"},
            new string[] { "音乐", "他喜欢音乐，也喜欢运动。", "yīn yuè", "âm nhạc", "âm nhạc"},
            new string[] { "影响", "把电视声音关小点儿，你弟弟明天考试，正在复习呢，别影响他。", "yǐng xiǎng", "ảnh hưởng", "ảnh hưởng"},
            new string[] { "应该", "同意，去年我就跟你说应该换一个新的了。", "yīng gāi", "ưng cai", "nên, cần phải"},
            new string[] { "用", "这个电子词典的作用大不大？", "yòng", "dụng", "dùng"},
            new string[] { "有名", "我这次来北京，只能住三天，所以我只能选择一两个最有名的地方去看看，以后有机会再去别的地方。", "yǒu míng", "hữu danh", "có tiếng"},
            new string[] { "游戏", "给他一块儿糖，或者和他做游戏。", "yóu xì", "du hí", "trò chơi"},
            new string[] { "又", "又下雪了！今年下过几次雪了？", "yòu", "hựu", "vừa, lại"},
            new string[] { "遇到", "下班后，在路上遇到一个老同学。", "yù dào", "ngộ đáo", "gặp phải"},
            new string[] { "愿意", "那还是我做饭吧，我愿意做饭。", "yuàn yì", "nguyện ý", "đồng ý"},
            new string[] { "越", "这个城市的环境变得越来越好了。", "yuè", "việt", "càng …"},
            new string[] { "月亮", "下面为大家唱歌的是王医生，歌的名字是《十五的月亮》，大家欢迎！", "yuè liang", "quyệt lượng", "trăng"},
            new string[] { "云", "今天是晴天，没有云。", "yún", "vân", "mây"},
            new string[] { "站", "没办法，我只能站在外面等休息时间。", "zhàn", "trạm", "trạm, ga, bến"},
            new string[] { "照顾", "这几天我不在家，小狗就请你帮我照顾了。", "zhào gu", "chiếu cố", "chăm sóc"},
            new string[] { "着急", "你一直看手表，有什么着急的事情吗？", "zháo jí", "trước cấp", "vội vã, sốt vó"},
            new string[] { "照相机", "你看见我的照相机了吗？", "zhào xiāng jī", "chiếu tương cơ", "máy ảnh"},
            new string[] { "照片", "那照片上的这个女孩儿是谁？", "zhào piàn", "chiếu phiến", "hình ảnh"},
            new string[] { "只", "不，我只有一个女儿。", "zhǐ", "chỉ", "chỉ"},
            new string[] { "终于", "我终于有了自己的大房子了，明天就可以搬家了。", "zhōng yú", "chung vu", "cuối cùng"},
            new string[] { "中间", "您站中间就可以了，好，再向左边一点儿，非常好！", "zhōng jiān", "trung gian", "chính giữa"},
            new string[] { "重要", "别难过了，考试成绩不是最重要的。", "zhòng yào", "trọng yếu", "quan trọng"},
            new string[] { "种", "您先看看这种颜色的怎么样？", "zhǒng", "chủng", "giống, loài, loại"},
            new string[] { "周末", "我的几个同事周末想去北京玩儿，但他们都不会开车。", "zhōu mò", "chu mạt", "cuối tuần"},
            new string[] { "祝", "那祝你在新的一年里学习更上一层楼。", "zhù", "chúc", "chúc"},
            new string[] { "主要", "男的主要是什么意思？", "zhǔ yào", "chủ yếu", "chủ yếu"},
            new string[] { "注意", "请大家注意，听力考试现在开始。", "zhù yì", "chú ý", "chú ý"},
            new string[] { "自己", "为了让自己更健康，他每天都花一个小时去锻炼身体。", "zì jǐ", "tự kỷ", "tự mình"},
            new string[] { "字典", "明天是妹妹的生日，我给她买了本汉语字典。", "zì diǎn", "tự điển", "tự điển"},
            new string[] { "总是", "他总是哭，有什么办法可以让他不哭吗？", "zǒng shì", "tổng thị", "lúc nào cũng, luôn luôn"},
            new string[] { "最近", "没关系，最近我不是开始跑步了吗？", "zuì jìn", "tối cận", "gần đây"},
            new string[] { "作用", "这个电子词典的作用大不大？", "zuò yòng", "tác dụng", "tác dụng"},
            new string[] { "作业", "我的作业早就完成了。", "zuò yè", "tác nghiệp", "bài tập, làm việc........"}
        };

        public static string[][] pages =
        {
            new string[] { "HSK 1 - Trang 01", "0", "27" },
            new string[] { "HSK 1 - Trang 02", "28", "55" },
            new string[] { "HSK 1 - Trang 03", "56", "83" },
            new string[] { "HSK 1 - Trang 04", "84", "111" },
            new string[] { "HSK 1 - Trang 05", "112", "139" },
            new string[] { "HSK 1 - Trang 06", "140", "152" },
            new string[] { "HSK 2 - Trang 07", "153", "184" },
            new string[] { "HSK 2 - Trang 08", "185", "216" },
            new string[] { "HSK 2 - Trang 09", "217", "248" },
            new string[] { "HSK 2 - Trang 10", "249", "280" },
            new string[] { "HSK 2 - Trang 11", "281", "302" },
            new string[] { "HSK 3 - Trang 12", "303", "332" },
            new string[] { "HSK 3 - Trang 13", "333", "362" },
            new string[] { "HSK 3 - Trang 14", "363", "392" },
            new string[] { "HSK 3 - Trang 15", "393", "422" },
            new string[] { "HSK 3 - Trang 16", "423", "452" },
            new string[] { "HSK 3 - Trang 17", "453", "482" },
            new string[] { "HSK 3 - Trang 18", "483", "512" },
            new string[] { "HSK 3 - Trang 19", "513", "542" },
            new string[] { "HSK 3 - Trang 20", "543", "572" },
            new string[] { "HSK 3 - Trang 21", "573", "600" }
        };
    }
}
